### ISSUE TITLE
CUDA out of memory even with samll batch size and feature size

### ISSUE THREAD

**Issue by Yunlong-He** [ShiZiqiang/dual-path-RNNs-DPRNNs-based-speech-separation#6]
root:/dual-path-RNNs-DPRNNs-based-speech-separation# CUDA_VISIBLE_DEVICES=0 python3 train.py --train_dir data/tr --valid_dir data/cv --sample_rate 8000 --segment 4 --cv_maxlen 6 --W 2 --N 32 --K 250 --D 6 --C 2 --E 128 --H 64 --norm_type gLN --causal 0 --mask_nonlinear relu --use_cuda 1 --epochs 100 --half_lr 1 --early_stop 0 --max_norm 5 --shuffle 1 --batch_size 1 --optimizer adam --lr 1e-3 --momentum 0 --l2 0 --save_folder exp/ --checkpoint 1 --continue_from "" --print_freq 1000

Training...
data_loader.len 1000
/lab/github/speech/dual-path-RNNs-DPRNNs-based-speech-separation/utils.py:45: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  frame = signal.new_tensor(frame).long()  # signal may in GPU or CPU
Epoch 1 | Iter 1 | Average Loss 4.806 | Current Loss 4.805784 | 577.1 ms/batch
-------------------------------------------------------------------------------------
Train Summary | End of Epoch 1 | Time 477.51s | Train Loss -40.387
-------------------------------------------------------------------------------------
Saving checkpoint model to exp/epoch1.pth.tar
Cross validation...
data_loader.len 100
Epoch 1 | Iter 1 | Average Loss -43.376 | Current Loss -43.375801 | 948.0 ms/batch
Traceback (most recent call last):
  File "train.py", line 138, in <module>
    main(args)
  File "train.py", line 132, in main
    solver.train()
  File "/lab/github/speech/dual-path-RNNs-DPRNNs-based-speech-separation/solver.py", line 77, in train
    val_loss = self._run_one_epoch(epoch, cross_valid=True)
  File "/lab/github/speech/dual-path-RNNs-DPRNNs-based-speech-separation/solver.py", line 150, in _run_one_epoch
    estimate_source = self.model(padded_mixture)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/lab/github/speech/dual-path-RNNs-DPRNNs-based-speech-separation/models.py", line 343, in forward
    score_ = self.separator(score_)  # B, nspk, T, N
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/lab/github/speech/dual-path-RNNs-DPRNNs-based-speech-separation/models.py", line 270, in forward
    output = self.DPRNN(enc_segments).view(batch_size * self.num_spk, self.feature_dim, self.segment_size,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/lab/github/speech/dual-path-RNNs-DPRNNs-based-speech-separation/models.py", line 156, in forward
    row_output = self.row_rnn[i](row_input)  # B*dim2, dim1, H
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/lab/github/speech/dual-path-RNNs-DPRNNs-based-speech-separation/models.py", line 100, in forward
    rnn_output, _ = self.rnn(output)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 577, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 1.07 GiB (GPU 0; 15.75 GiB total capacity; 14.05 GiB already allocated; 93.56 MiB free; 14.47 GiB reserved in total by PyTorch)

**Comment by ShiZiqiang** [comment]
Thanks for using. Please try --cv_maxlen 4  or use a GPU with larger memory, e.g. 24GB.

**Comment by Yunlong-He** [comment]
thanks, Shiziqiang, I finally found that I am handling very long speech file, which makes a sample very big, after spliting by vad, it works well now.
